swift-nav/swift-toolbox

console_backend/src/tabs/main_tab.rs
console_backend/src/utils.rs
resources/LoggingBar.qml
src/main/resources/base/console_backend.capnp
swiftnav_console/main.py

add stop event to trigger reset of logging counter

reset recording bar counter [CPP-850]

---

Makefile.toml

removes:
- qmlls (qml language server https://doc.qt.io/qtcreator/creator-language-servers.html)
- qmlformat
total: 12 mb
from dist (linux / mac)
this was the underlying cause to macOS signing issue as they are not codesigned (refer to https://swift-nav.atlassian.net/browse/CPP-857?focusedCommentId=70192)

purge qmlformat and qmlls from dist [CPP-857]

---

README.md
console_backend/tests/data/console-capnp-20220419-033358.pickle
src/main/resources/base/console_backend.capnp
utils/loop_generate_core.sh

just a small hack related to LogLevel#error being generated to conflict `Self::Error`, 
since we hotfixed this in the #917 by using text instead of enums (think that takes more bytes), this enum is no longer needed.

remove loglevel enum [CPP-884]

---

.github/workflows/main.yml
Makefile.toml

settings table scrolling is laggy on 6.4.1, downgrading back to 6.3.2 works fine.
should have no compatibility issues reverting.

downgrade pyside from 6.4.1 to 6.3.2 [CPP-905]

---

console_backend/src/tabs/tracking_tab/tracking_sky_plot_tab.rs

for the file attached in ticket gives elevation angle of -91 which causes
```
thread '<unnamed>' panicked at 'attempt to subtract with overflow', console_backend/src/tabs/tracking_tab/tracking_sky_plot_tab.rs:87:25
```
since sbp docs say elevation is supposed to be (-90, 90), will just skip on these invalid values.

skip invalid elevation angle [CPP-895]

---

resources/SettingsTabComponents/SettingsPane.qml
swiftnav_console/main.py

https://doc.qt.io/qt-6/qml-qtquick-doublevalidator.html#locale-prop
https://doc.qt.io/qt-6/qml-qtqml-qt.html#locale-method
enforce C locale to prevent typing '1,234' vs '1.234' on different keyboard layouts

set validator locale to C [CPP-886]

---

console_backend/src/cli_options.rs
resources/Constants/Globals.qml
resources/SolutionTab.qml
swiftnav_console/main.py

apparently tab loads are lazy.
so we can basically just remove the tab from layout.
tested with javascript logging 'loaded' msg that only pops up whenever you click into the map.
also means all the concerns about performance previously can be disregarded. is actually pretty good not as bad as imagined.

add --disable-map cli option [CPP-911]

---

console_backend/src/process_messages.rs
console_backend/src/tabs/solution_tab/solution_position_tab.rs
console_backend/src/types.rs
resources/SolutionTabComponents/SolutionMapTab.qml
resources/web/map/js/trajectory.js
resources/web/map/js/trajectory_raw.js
src/main/resources/base/console_backend.capnp
swiftnav_console/main.py
swiftnav_console/solution_map.py

https://docs.mapbox.com/help/troubleshooting/mapbox-gl-js-performance/
- disables sending metrics to mapbox
- enables optimize base styles
- enables attribute use desktop opengl
- half required points to draw ellipse (might be better to scale this w.r.t distance on map since small circles looks ok rendering ~ 8 points)

improve map performance [CPP-916]

---

console_backend/src/constants.rs
console_backend/src/tabs/solution_tab/solution_position_tab.rs

add speed to solutions table.
not an ideal display for the HUD / quickview but includes some additional values.
an idea for the quickview might be to just allow rearranging of entries in table or focusing multiple values when shift clicking etc and will highlight / enlarge. this might be the best option as it does not add additional UI changes.

add total velocity to table [CPP-908]

---

resources/SettingsTab.qml
resources/SettingsTabComponents/SettingsTable.qml
swiftnav_console/settings_tab.py

remove timers from settings view

---

Makefile.toml

Helvetica was not available on my Ubuntu 22.04 system, so this was the best workaround available.

build: support imagemagick on Ubuntu 22.04

---

console_backend/src/cli_options.rs
resources/Constants/Globals.qml
resources/SolutionTab.qml
swiftnav_console/main.py

as per memory / cpu usage request, disables map by default

disabled on default, swap to --enable-map

---

.github/workflows/main.yml
.gitignore
Makefile.toml
README.debug.md
README.md
console_backend/setup.py
entrypoint/src/main.rs
installers/Windows/Installer.nsi
standalone-py/.gitignore
utils/debug_intermittent_startup_crash.sh
utils/find_intermittent_startup_crash.ps1
utils/symlink-qt-installer-libs-to-pyside6.sh

Try bumping to Python 3.11 one more time.
Related PR: https://github.com/swift-nav/swift-toolbox-ci/pull/9
Test build of installers here: https://github.com/swift-nav/swift-toolbox/releases/tag/v4.0.9-py311
Jira: https://swift-nav.atlassian.net/browse/CPP-882

python: try bumping to Python 3.11 again [CPP-882]

---

resources/SettingsTabComponents/SettingsPane.qml

some how `text` gets persisted even when changing panes
this should fix the sticky value bug. which changing values on double/float causes it to fix the value even when looking at other setting entries

fix sticky settings value bug [CPP-923]

---

console_backend/src/status_bar.rs
resources/SettingsTabComponents/SettingsPane.qml

https://github.com/swift-nav/swift-toolbox/pull/1050#issuecomment-1557660648

combine note+desc in settings, add dash to title

---

Makefile.toml

Recent versions of choco appear to have introduced a behavior change
which is producing the following error in CI:
Package name cannot be a path to a file on a remote, or local file system.
To install a local, or remote file, you may use:
choco install imagemagick.tool --version="7.1.0" --source="D:\a\swift-toolbox\swift-toolbox"
[cargo-make] ERROR - Error while running duckscript: Source: Unknown Line: 5 - Error while executing command, exit code: 1
[cargo-make] WARN - Build Failed.
Error: Process completed with exit code 1.
This updates CI to account for this behavior change.

ci: update imagemagick install cmd for windows

---

.github/workflows/main.yml

There was an issue downloading the sha for some of the Qt archives for github actions related to the aqt dependency. The suggested fix was here:
https://github.com/jurplel/install-qt-action/issues/187

Fix issue with InstallQt Github Action

---

console_backend/src/cli_options.rs
console_backend/src/log_panel.rs
console_backend/src/shared_state.rs

* Handle bad log messages. When the console starts with Debug logging enabled there were a few messages that have escaped quotation chars which would cause the console to crash so this regex should remove those.
* Add cli argument for setting the log level, on master the default log level was WARNING so no lower-level warnings would get dumped to a file/console until you start the console and then set the level. I think adding this as an argument is pretty reasonable, but if there is pushback, we can set it as hidden.
* Add cli argument for dumping logs to stdout. I find it is much easier to debug an issue if we can dump the logs to a terminal window instead of a separate log file every time the console starts. Again if there is pushback we can set the argument to hidden.

Handle bad log messages, add log-level,log-stdout cli args

---

console_backend/src/process_messages.rs
console_backend/src/tabs/tracking_tab/tracking_signals_tab.rs

* Adds handle_msg_status_report to the TrackingSignalsTab to discern whether the source device is a PGM.
* If the device is a PGM, we disable the processing of MsgTrackingState and MsgMeasurementState in favor of MsgObs.
* There is a slight visual artifact at the beginning of the stream which is due to the delayed reception of the MsgStatusReport but after the message is received things look normal.
[Screencast from 07-21-2023 07:10:02 PM.webm](https://github.com/swift-nav/swift-toolbox/assets/43353147/1afff5f3-e7b5-4940-a22e-491d62b54b4d)

Support PGM in tracking signals tab[DIP-64]

---

console_backend/src/process_messages.rs
console_backend/src/tracking_signals_tab.rs

Cherry-pick:
- Support PGM in tracking signals tab[DIP-64] (#1115)

Support PGM in tracking signals tab[DIP-64][v4.0.x]

---

resources/SolutionTab.qml
shell.nix
swiftnav_console/main.py

Allows the console be built and run on NixOS.  I could not get the WebView to work and attempting to load it would cause the process to crash, so additional work was needed to avoid loading it altogether.
Basic usage on NixOS:
```
nix-shell
cargo make run
```

feat: enable running on NixOS

---

Cargo.lock
console_backend/Cargo.toml
console_backend/src/tabs/advanced_tab/advanced_networking_tab.rs
shell.nix

baudrate settings dropdown [DIP-247]

---

Cargo.lock
console_backend/Cargo.toml
console_backend/src/advanced_imu_tab.rs
console_backend/src/advanced_networking_tab.rs
console_backend/src/baseline_tab.rs
console_backend/src/date_conv.rs
console_backend/src/solution_tab.rs

adds tdkicm42670
baudrate enum dropdown
update deps
for 4.0 version

[v4.0] update deps, add TdkIcm42670, baudrate to enum dropdown [DIP-247]

---

Makefile.toml

This PR installs taplo-cli with the tip described [here](https://taplo.tamasfe.dev/cli/installation/cargo.html). Namely you should use `--locked` if you are getting compliation errors (and we were).
I also chose to lock taplo to v0.8.1. It would be trivial to switch this to take the latest.

fix taplo version@0.8.1 & resolve compilation errors with --locked

---

.github/workflows/main.yml
README.md
console_backend/src/fft_monitor.rs
console_backend/src/tabs/advanced_tab/advanced_spectrum_analyzer_tab.rs
console_backend/src/tabs/advanced_tab/advanced_system_monitor_tab.rs
console_backend/src/tabs/baseline_tab.rs
console_backend/src/tabs/observation_tab.rs
console_backend/src/tabs/settings_tab.rs
console_backend/src/tabs/solution_tab/solution_position_tab.rs
console_backend/src/tabs/update_tab.rs
pyproject.toml
utils/glob.ds

* Clippy fixes.
* Fixed an issue with new cargo make duckscript. We were character escaping a boolean which seems to be invalid now. Fixing this now allows the correct collection of python files to be globbed for python checks to run.
* Uprev macos-11 to macos-12 due to deprecation.

Collection of fixes to get CI running.
